## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Tue Sep 04 13:32:50 ICT 2018
systemProp.http.proxyPassword=Kopi,2018
systemProp.http.proxyHost=10.2.0.201
systemProp.http.nonProxyHosts=localhost;10.2.*.*;*.ut;*.unitedtractors.com;apps.unitedtractors.com;angular.io;*angularjs.org;cli.angular.io;sourcecode.unitedtractors.com;*github.com;loopback.io;material.angular.io;*mongodb.com;*google.com;*npmjs.org;*detik.com;*outlook.com;*mysql.com;*postgresql.org;*enterprisedb.com;*github.io
#org.gradle.jvmargs=-Xmx512m
systemProp.http.proxyUser=cst_dev38
systemProp.http.proxyPort=8080
org.gradle.jvmargs=-Xmx2048M -XX\:MaxHeapSize\=8g
android.useAndroidX=true
android.enableJetifier=true
#org.gradle.java.home=C:\\Program Files\\Java\\jdk-17